import Map, { type MapProps } from '@/components/maps/generic-map';

export const stateCode = [
  'Russia Asia',
  'United Arab Emirates',
  'Afghanistan',
  'American Samoa',
  'Bangladesh',
  'Bahrain',
  'Brunei Darussalam',
  'Bhutan',
  'Cocos (Keeling) Islands',
  'China',
  'Christmas Island',
  'Federated States of Micronesia',
  'Guam',
  'Hong Kong',
  'Indonesia',
  'Israel',
  'India',
  'British Indian Ocean Territory',
  'Iraq',
  'Iran',
  'Jordan',
  'Japan',
  'Kyrgyzstan',
  'Cambodia',
  'North Korea',
  'South Korea',
  'Kuwait',
  'Kazakhstan Asia',
  "Lao People's Democratic Republic",
  'Lebanon',
  'Sri Lanka',
  'Marshall Islands',
  'Macau',
  'Myanmar',
  'Mongolia',
  'Northern Mariana Islands',
  'Mauritius',
  'Maldives',
  'Malaysia',
  'Nepal',
  'Nauru',
  'Niue',
  'Oman',
  'Papua New Guinea',
  'Philippines',
  'Pakistan',
  'Palestinian Territories',
  'Palau',
  'Qatar',
  'Saudi Arabia',
  'Solomon Islands',
  'Seychelles',
  'Singapore',
  'Syria',
  'Thailand',
  'Tajikistan',
  'Tokelau',
  'Timor-Leste',
  'Turkmenistan',
  'Tuvalu',
  'Taiwan',
  'Baker Island',
  'Howland Island',
  'Johnston Atoll',
  'Midway Islands',
  'Wake Island',
  'Uzbekistan',
  'Vietnam',
  'Vanuatu',
  'Wallis and Futuna',
  'Samoa',
  'Yemen',
];

export interface AsiaProps extends Omit<MapProps, 'stateCode'> {}

const Asia = (props: AsiaProps) => {
    return <Map name='Asia' stateCode={stateCode} {...props} />;
};

export default Asia;
