import Map, { type MapProps } from '@/components/maps/generic-map';

export const stateCode = [
  'Russia Europe',
  'Gibraltar',
  'Netherlands',
  'Vatican City',
  'Cyprus',
  'Ukraine',
  'Turkey',
  'Sweden',
  'Slovenia',
  'Slovakia',
  'Serbia',
  'San Marino',
  'Romania',
  'Portugal',
  'Poland',
  'Svalbard and Jan Mayen',
  'Norway',
  'Montenegro',
  'Malta',
  'Macedonia',
  'Moldova',
  'Monaco',
  'Latvia',
  'Luxembourg',
  'Lithuania',
  'Liechtenstein',
  'Kosovo',
  'Jersey',
  'Iceland',
  'Ireland',
  'Isle of Man',
  'Hungary',
  'Croatia',
  'Greece',
  'Guernsey',
  'Georgia',
  'France',
  'Faroe Islands',
  'Finland',
  'Estonia',
  'Spain',
  'United Kingdom',
  'Denmark',
  'Germany',
  'Czech Republic',
  'Switzerland',
  'Belarus',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Belgium',
  'Azerbaijan',
  'Austria',
  'Armenia',
  'Andorra',
  'Aland Islands',
  'Albania',
  'Italy',
  'Kazakhstan Europe',
];

export interface EuropeProps extends Omit<MapProps, 'stateCode'> {}

const Europe = (props: EuropeProps) => {
    return <Map stateCode={stateCode} {...props} />;
};

export default Europe;
